/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guagua_ffmpegapp1_MainActivity */

#ifndef _Included_com_guagua_ffmpegapp1_MainActivity
#define _Included_com_guagua_ffmpegapp1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guagua_ffmpegapp1_MainActivity
 * Method:    nativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guagua_ffmpegapp1_MainActivity_nativeString
  (JNIEnv *env, jobject obj);


JNIEXPORT jstring JNICALL Java_com_guagua_ffmpegapp1_MainActivity_nativeGetViewInfo
        (JNIEnv *env, jobject obj,jobject jobject1);

#ifdef __cplusplus
}
#endif
#endif
