/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_guagua_ffmpegapp1_MainActivity.h"
#include <string.h>
#include <stdio.h>
#include "include/libavcodec/avcodec.h"
/* Header for class com_guagua_ffmpegapp1_MainActivity */


JNIEXPORT jstring JNICALL Java_com_guagua_ffmpegapp1_MainActivity_nativeString
        (JNIEnv *evn, jobject obj) {
    char info[10000] = {0};


    sprintf(info, "%s\n", avcodec_configuration());
    return (*evn)->NewStringUTF(evn, info);
}

JNIEXPORT JNIEXPORT jstring JNICALL Java_com_guagua_ffmpegapp1_MainActivity_nativeGetViewInfo
        (JNIEnv *env, jobject obj, jobject jobject1) {
    char info[10000] = {0};

    avcodec_register_all();
    jstring filePath=(*env)->NewStringUTF(env,jobject1);
    printf("file:  %s",filePath);


    return (*env)->NewStringUTF(env, info);
}